---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*.md"
- type: heading
  label: Data
- type: document
  path: src/_data/settings.yaml
  label: Setting
- type: document
  path: src/_data/quicklinks.yaml
  label: Links
- type: document
  path: src/_data/navigation.yaml
  label: Menu
upload_dir: src/static/img
public_path: "/static/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run start
