name: Build Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Check if secrets exist 1
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
        if: ${{ env.TINA_PUBLIC_CLIENT_ID == '' }}
        run: 'echo TINA_PUBLIC_CLIENT_ID secret not present'

      - name: Check if secrets exist 2
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
        if: ${{ env.TINA_TOKEN == '' }}
        run: 'echo TINA_TOKEN secret not present'

      - name: Check if secrets exist 3
        env:
          TINA_SEARCH_TOKEN: ${{ secrets.TINA_SEARCH_TOKEN }}
        if: ${{ env.TINA_SEARCH_TOKEN == '' }}
        run: 'echo TINA_SEARCH_TOKEN secret not present'

      - name: Install dependencies & build
        env:
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          TINA_SEARCH_TOKEN: ${{ secrets.TINA_SEARCH_TOKEN }}
        run: |
          yarn install
          yarn build

      # The local gitignore generated by TinaCMS is an issue, because the admin files aren't included in the 'Deploy' step below.
      - name: Delete tinaCMS gitignore
        run: rm ./_site/admin/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
